[colors.primary]
background = "#000000"

[font]
size = 12

[font.normal]
family = "BlexMono Nerd Font Mono"

[selection]
save_to_clipboard = false

[window]
opacity = 0.70

[window.padding]
x = 15
y = 15
