# Hyprland Window Rules Configuration

# Calculator window
windowrule = float on, match:title ^(Calculator)$

# Calendar window
windowrule = float on, match:title ^(Calendar)$

# JetBrains IDE windows
windowrule = float on, match:float 0, match:class ^(jetbrains-.*), match:title ^(win.*)
windowrule = float on, match:class ^(jetbrains-.*), match:title ^(Welcome to.*)
windowrule = center on, match:class ^(jetbrains-.*), match:title ^(Replace All)$
# windowrulev2 = allowsinput, class:^(jetbrains-.*)

# Bitwarden window
windowrule = float on, match:title ^(.*Bitwarden.*)
