# Hyprland Window Rules Configuration

# Calculator window
windowrulev2 = float, title:^(Calculator)$

# Calendar window
windowrulev2 = float, title:^(Calendar)$

# JetBrains IDE windows
windowrulev2 = float, floating:0, class:^(jetbrains-.*),title:^(win.*)
windowrulev2 = float, class:^(jetbrains-.*),title:^(Welcome to.*)
windowrulev2 = center, class:^(jetbrains-.*),title:^(Replace All)$
# windowrulev2 = allowsinput, class:^(jetbrains-.*)

# Bitwarden window
windowrulev2 = float, title:^(.*Bitwarden.*)